webtalk_init -webtalk_dir C:/Users/Soph/Documents/College/Senior/EE119c/FMReceiver/FMReceiver.sim/sim_1/behav/xsim/xsim.dir/MixerTB_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu May  9 06:29:54 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "3922d13c-3a70-4889-a304-99abb3ae0e7d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "cd67f6c96fad4eb5a4af69b12edb443d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "228" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2592 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "11609932500 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "37.84_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "16152_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3109918534 -regid "" -xml C:/Users/Soph/Documents/College/Senior/EE119c/FMReceiver/FMReceiver.sim/sim_1/behav/xsim/xsim.dir/MixerTB_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Soph/Documents/College/Senior/EE119c/FMReceiver/FMReceiver.sim/sim_1/behav/xsim/xsim.dir/MixerTB_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Soph/Documents/College/Senior/EE119c/FMReceiver/FMReceiver.sim/sim_1/behav/xsim/xsim.dir/MixerTB_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
